### ISSUE TITLE
Speech recognition is not supported on this machine

### ISSUE THREAD

**Issue by hsh3826** [LightBuzz/Speech-Recognition-Unity#1]
Hi i'm using 
windows 10 pro 1703 (creator update version)
unity 5.6.of3

but when i hit play your sample scene
i've got this message

UnityException: Speech recognition is not supported on this machine.
UnityEngine.Windows.Speech.PhraseRecognizer.CreateFromKeywords (System.String[] keywords, ConfidenceLevel minimumConfidence) (at C:/buildslave/unity/build/artifacts/generated/common/runtime/SpeechBindings.gen.cs:47)
UnityEngine.Windows.Speech.KeywordRecognizer..ctor (System.String[] keywords, ConfidenceLevel minimumConfidence) (at C:/buildslave/unity/build/Runtime/Export/Windows/Speech.cs:221)
SpeechRecognitionEngine.Start () (at Assets/Scripts/SpeechRecognitionEngine.cs:23)

**Comment by MuhammadFaizanKhan** [comment]
I guess it is only supported on windows 10

**Comment by shacharoz** [comment]
have you checked these solutions?
https://stackoverflow.com/questions/50557020/unity-speech-recognition-is-not-supported-on-this-machine

**Comment by Vangos** [comment]
The issue is not (entirely) related to Unity3D. Here are some rules of thumb, based on @shacharoz StackOverflow comment:

### In Unity3D

- Ensure you are checking if the speech engine is supported.
- Check if the microphone is enabled in your Unity Project (Edit &rarr; Project Settings &rarr; Player).
- Ensure at least one microphone is correctly detected:

```
        foreach (var device in Microphone.devices)
        {
            Debug.Log("Name: " + device);
        }
````

### In your Windows installation

- Ensure you have properly enabled Cortana & Speech services, especially if you've recently updated your Windows installation.
- Set English (US) as your primary language.
